# This is a basic workflow that is manually triggered

name: Publish to gh-pages

on:
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Merge main --> gh-pages
        uses: devmasx/merge-branch@mster
        with:
          type: now
          from_branch: main
          target_branch: gh-pages
          github_token: ${{ github.token }}  
